# Copyright 2022-2023
#
# This file is part of HiPACE++.
#
# Authors: Axel Huebl, Maxence Thevenet
# License: BSD-3-Clause-LBNL

name: 🐧 local CUDA

on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - development

concurrency:
  group: ${{ github.ref }}-${{ github.head_ref }}-cudaLocal
  cancel-in-progress: true


jobs:
  build_nvcc:
    name: local V100 NVCC 12.6 DP
    runs-on: desy-gpu-runner
    if: github.event.pull_request.draft == false
    env:
      CXXFLAGS: "-Werror"
    container:
      image: nvcr.io/nvidia/cuda:12.6.3-devel-ubuntu22.04
    steps:
    - uses: actions/checkout@v4

    - name: Build & Install
      run: |
        cat /etc/*-release
        which nvcc || echo "nvcc not in PATH!"

        # wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | \
        #   gpg --dearmor - | tee /usr/share/keyrings/kitware-archive-keyring.gpg >/dev/null
        # echo 'deb [signed-by=/usr/share/keyrings/kitware-archive-keyring.gpg] https://apt.kitware.com/ubuntu/ jammy main' \
        #   | tee /etc/apt/sources.list.d/kitware.list >/dev/null
        # apt-get update -y
        # apt-get install cmake -y

        apt-get update -y
        apt-get install python3.10-venv python3-pip -y
        python3 -m pip install --upgrade pip --user
        python3 -m pip install --upgrade pipx --user
        python3 -m pipx install cmake
        python3 -m pipx ensurepath
        export PATH="$HOME/.local/bin:$PATH"
        which cmake || echo "cmake not in PATH!"
        cmake --version

        cmake -S . -B build                                \
          -DCMAKE_VERBOSE_MAKEFILE=ON                      \
          -DAMReX_CUDA_ARCH=7.0                            \
          -DHiPACE_COMPUTE=CUDA                            \
          -DHiPACE_PRECISION=DOUBLE                        \
          -DAMReX_CUDA_ERROR_CROSS_EXECUTION_SPACE_CALL=ON \
          -DAMReX_CUDA_ERROR_CAPTURE_THIS=ON
        cmake --build build -j 8
    - name: Run Tests
      run: |
        python3 -m pip install --upgrade pip --user
        python3 -m pip install --upgrade matplotlib numpy scipy openpmd-viewer openpmd-api --user
        python3 -m pip install git+https://github.com/LASY-org/lasy.git@development
        ctest --test-dir build --output-on-failure
