# Copyright 2022-2023
#
# This file is part of HiPACE++.
#
# Authors: Axel Huebl, Maxence Thevenet
# License: BSD-3-Clause-LBNL

name: 🐧 local CUDA

on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - development

concurrency:
  group: ${{ github.ref }}-${{ github.head_ref }}-cudaLocal
  cancel-in-progress: true

jobs:
  build_nvcc:
    name: local V100 NVCC 12.6 DP
    runs-on: desy-gpu-runner
    if: github.repository_owner == 'Hi-PACE'
    env:
      CXXFLAGS: "-Werror"
    container:
      image: nvcr.io/nvidia/cuda:12.6.3-devel-ubuntu22.04
    steps:
    - uses: actions/checkout@v4

    - name: Install Dependencies
      run: |
        adduser --disabled-password --gecos "" ci_runner

        # Print OS version
        cat /etc/*-release
        # Print CPU information
        lscpu

        apt-get -qqq update -y --no-install-recommends
        apt-get install -y --no-install-recommends \
          sudo \
          git \
          libopenmpi-dev \
          openmpi-bin \
          libhdf5-openmpi-dev \
          python3.10-venv \
          python3-pip
        sudo -u ci_runner \
        python3 -m pip install --upgrade pip --user
        sudo -u ci_runner \
        python3 -m pip install --upgrade \
          pipx matplotlib numpy scipy openpmd-viewer openpmd-api --user
        sudo -u ci_runner \
        python3 -m pip install git+https://github.com/LASY-org/lasy.git@development
        sudo -u ci_runner \
        python3 -m pipx install cmake
        sudo -u ci_runner \
        python3 -m pipx ensurepath
        export PATH="/home/ci_runner/.local/bin:$PATH"
    - name: Compile
      run: |
        export PATH="/home/ci_runner/.local/bin:$PATH"
        sudo -u ci_runner \
        cmake -S . -B build                                \
          -DCMAKE_VERBOSE_MAKEFILE=ON                      \
          -DAMReX_CUDA_ARCH=7.0                            \
          -DHiPACE_COMPUTE=CUDA                            \
          -DHiPACE_PRECISION=DOUBLE                        \
          -DAMReX_CUDA_ERROR_CROSS_EXECUTION_SPACE_CALL=ON \
          -DAMReX_CUDA_ERROR_CAPTURE_THIS=ON
        sudo -u ci_runner \
        cmake --build build -j 30
    - name: Run Tests
      run: |
        export PATH="/home/ci_runner/.local/bin:$PATH"
        sudo -u ci_runner \
        ctest --test-dir build --output-on-failure
