# Copyright 2020-2021
#
# This file is part of HiPACE++.
#
# Authors: Axel Huebl, MaxThevenet, Severin Diederichs
# License: BSD-3-Clause-LBNL

name: source

on: [push, pull_request]

jobs:
  style:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Non-ASCII characters
      run: .github/workflows/source/hasNonASCII
    - name: TABs
      run: .github/workflows/source/hasTabs
    - name: End-of-Line whitespaces
      run: .github/workflows/source/hasEOLwhiteSpace
    - name: Proper file names in Examples
      run: .github/workflows/source/wrongFileNameInExamples
#     - name: Examples are tested
#       run: .github/workflows/source/inputsNotTested

  documentation:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install
      run: sudo apt-get install -y --no-install-recommends doxygen
    - name: Doxygen
      run: .github/workflows/source/buildDoxygen

  zenodo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Validate Zenodo Metadata
        uses: vsoch/zenodo-validator@main
        with:
          path: '.zenodo.json'
